language: java

env:
- VERSION=1.6.4  BUILD=9.11.1.1345         EXT=src
- VERSION=1.7.2  BUILD=10.12.2.1121        EXT=src
- VERSION=1.7.10 BUILD=10.13.4.1558-1.7.10 EXT=src
- VERSION=1.8    BUILD=11.14.4.1577        EXT=mdk
- VERSION=1.8.8  BUILD=11.15.0.1609-1.8.8  EXT=mdk

install:
- wget http://files.minecraftforge.net/maven/net/minecraftforge/forge/$VERSION-$BUILD/forge-$VERSION-$BUILD-$EXT.zip
- unzip -n forge-$VERSION-$BUILD-$EXT.zip
- ./gradlew setupCIWorkspace
